version: '3.2'

services:
  server:
    build:
      context: ./socket-server
    image: ss
    volumes:
      - type: bind
        source: ./socket-server
        target: /var/www/html
    ports:
      - "8081:8080"
    environment:
        XDEBUG_CONFIG: remote_host=192.168.1.7

  client:
    build:
      context: ./socket-client
    image: sc
    volumes:
      - type: bind
        source: ./socket-client
        target: /var/www/html
    ports:
      - "8080:80"