version: '3.2'

services:
  server:
    build: ./socket-server
    image: ss
    #volumes:
    #  - type: bind
    #    source: ./socket-server/src
    #    target: /var/www/html
    ports:
      - "8081:8080"

  client:
    build: ./socket-client
    image: sc
    #volumes:
    #  - type: bind
    #    source: ./socket-client/src
    #    target: /var/www/html
    ports:
      - "8080:80"